server:
  port: 8803
spring:
  application:
    name: Resource
security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://localhost:8801/auth/user
eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8800/register/eureka/