server:
  port: 9090
  servlet:
    context-path: /official
spring:
  application:
    name: Official
  security:
    user:
      name: admin
      password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zgcenv?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
    hikari:
      connection-timeout: 30000
      max-lifetime: 1800000
      max-pool-size: 15
      min-idle: 5
      connection-test-query: select 1
      pool-name: FebsHikariCP
  groovy:
    template:
      check-template-location: false
mybatis:
  #开启驼峰命名法
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  type-aliases-package: com.zgcenv.elip.official.entity
  mapper-locations: classpath*:mapper/*Dao.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: null
  global-config:
    banner: true
snowFlake:
  workerId: 1
  dataCenterId: 1
jwt:
  secret: javainuse
swagger:
  enable: true